/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from '@react-three/drei'
import { useRef } from 'react'
import * as THREE from 'three'
import { GLTF } from 'three-stdlib'

type GLTFResult = GLTF & {
  nodes: {
    body: THREE.Mesh
    Object: THREE.Mesh
    Circle003: THREE.Mesh
    Circle003_1: THREE.Mesh
    Circle005: THREE.Mesh
    Circle005_1: THREE.Mesh
    volume_sensitivity_button: THREE.Mesh
    Cube042: THREE.Mesh
    Cube042_1: THREE.Mesh
    Cube000: THREE.Mesh
    Cube000_1: THREE.Mesh
    Cube000_2: THREE.Mesh
    Cube000_3: THREE.Mesh
    Cube041: THREE.Mesh
    Cube041_1: THREE.Mesh
    Cube041_2: THREE.Mesh
    Cube041_3: THREE.Mesh
    Base: THREE.Mesh
    Base_1: THREE.Mesh
    Base_2: THREE.Mesh
    Base_3: THREE.Mesh
    Base_4: THREE.Mesh
    Cube_Cube001: THREE.Mesh
    Cube_Cube001_1: THREE.Mesh
    Cube_Cube001_2: THREE.Mesh
    Cube_Cube001_3: THREE.Mesh
    Cube_Cube001_4: THREE.Mesh
    Cube_Cube001_5: THREE.Mesh
    Cube_Cube001_6: THREE.Mesh
    Cube_Cube001_7: THREE.Mesh
    Cube_Cube001_8: THREE.Mesh
    Cube_Cube001_9: THREE.Mesh
    Cube_Cube001_10: THREE.Mesh
    Cube_Cube001_11: THREE.Mesh
    Audio_Interface: THREE.Mesh
    inside_darkening_cube: THREE.Mesh
    faceplate_back: THREE.Mesh
    back_fixing_screws: THREE.Mesh
    dock_connector: THREE.Mesh
    Cube005: THREE.Mesh
    Cube005_1: THREE.Mesh
    hybrid_jack_1: THREE.Mesh
    hybrid_jack_2: THREE.Mesh
    hybrid_jacks_fixing_srews: THREE.Mesh
    Circle009: THREE.Mesh
    Circle009_1: THREE.Mesh
    Circle008: THREE.Mesh
    Circle008_1: THREE.Mesh
    Cube006: THREE.Mesh
    Cube006_1: THREE.Mesh
    faceplate_front: THREE.Mesh
    Sphere015: THREE.Mesh
    Sphere015_1: THREE.Mesh
    Sphere017: THREE.Mesh
    Sphere017_1: THREE.Mesh
    Sphere016: THREE.Mesh
    Sphere016_1: THREE.Mesh
    front_fixing_screws: THREE.Mesh
    Circle010: THREE.Mesh
    Circle010_1: THREE.Mesh
    Circle011: THREE.Mesh
    Circle011_1: THREE.Mesh
    knob_gain_1: THREE.Mesh
    Sphere003: THREE.Mesh
    knob_gain_2: THREE.Mesh
    Sphere002: THREE.Mesh
    knob_phones_2: THREE.Mesh
    Sphere001: THREE.Mesh
    leds_green: THREE.Mesh
    leds_red: THREE.Mesh
    leds_yellow: THREE.Mesh
    onyx_knob_body: THREE.Mesh
    onyx_knob_cap: THREE.Mesh
    Calligaris_Relax_Sofas_Maurice_CS33462525_Component_01: THREE.Mesh
    Calligaris_Relax_Sofas_Maurice_CS33462525_Component_01_1: THREE.Mesh
    HSeatPan: THREE.Mesh
    HSeatPan_1: THREE.Mesh
    HSeatPan_2: THREE.Mesh
    HSeatPan_3: THREE.Mesh
    HSeatPan_4: THREE.Mesh
    ['G-__555699']: THREE.Mesh
    ['G-__555699_1']: THREE.Mesh
    ['G-__555564']: THREE.Mesh
    ['G-__555564_1']: THREE.Mesh
    ['G-__555609']: THREE.Mesh
    ['G-__555609_1']: THREE.Mesh
    ['G-__555690']: THREE.Mesh
    ['G-__555690_1']: THREE.Mesh
    ['G-__555690_2']: THREE.Mesh
    Cylinder: THREE.Mesh
    Cylinder_1: THREE.Mesh
    Cylinder_2: THREE.Mesh
    Cylinder_3: THREE.Mesh
    Cylinder_4: THREE.Mesh
    ['G-__555762']: THREE.Mesh
    ['G-__555762_1']: THREE.Mesh
    Name: THREE.Mesh
    Plane: THREE.Mesh
    Plane_1: THREE.Mesh
    Plane_2: THREE.Mesh
    Plane_3: THREE.Mesh
    Plane_4: THREE.Mesh
    Plane_5: THREE.Mesh
    Big_Buttons001: THREE.Mesh
    Big_Buttons001_1: THREE.Mesh
    Big_Buttons001_2: THREE.Mesh
    camera001: THREE.Mesh
    camera001_1: THREE.Mesh
  }
  materials: {
    ['Black metal body']: THREE.MeshStandardMaterial
    ['Black metal']: THREE.MeshStandardMaterial
    red: THREE.MeshStandardMaterial
    ['Black metal inside']: THREE.MeshStandardMaterial
    body: THREE.MeshStandardMaterial
    ['Black Metal']: THREE.MeshPhysicalMaterial
    ['White Light']: THREE.MeshStandardMaterial
    ['Matte White']: THREE.MeshStandardMaterial
    ['body.001']: THREE.MeshStandardMaterial
    ['Black Metal.001']: THREE.MeshPhysicalMaterial
    ['White Light.001']: THREE.MeshStandardMaterial
    ['Matte White.001']: THREE.MeshStandardMaterial
    ['Material.026']: THREE.MeshStandardMaterial
    None: THREE.MeshStandardMaterial
    ['Material.027']: THREE.MeshStandardMaterial
    ['Material.025']: THREE.MeshStandardMaterial
    clear_rubber: THREE.MeshStandardMaterial
    ['Material.029']: THREE.MeshStandardMaterial
    ['Material.030']: THREE.MeshStandardMaterial
    ['Material.033']: THREE.MeshStandardMaterial
    ['Material.032']: THREE.MeshStandardMaterial
    ['Material.037']: THREE.MeshStandardMaterial
    ['Material.036']: THREE.MeshStandardMaterial
    ['Material.035']: THREE.MeshStandardMaterial
    ['Material.034']: THREE.MeshStandardMaterial
    ['Material.041']: THREE.MeshStandardMaterial
    ['Material.038']: THREE.MeshStandardMaterial
    ['Material.045']: THREE.MeshStandardMaterial
    ['Material.042']: THREE.MeshStandardMaterial
    ['Material.050']: THREE.MeshStandardMaterial
    jacks_noir: THREE.MeshStandardMaterial
    ['Material.053']: THREE.MeshStandardMaterial
    ['Material.049']: THREE.MeshStandardMaterial
    chrome: THREE.MeshStandardMaterial
    ['48V']: THREE.MeshStandardMaterial
    ['Material.051']: THREE.MeshStandardMaterial
    ['Material.052']: THREE.MeshStandardMaterial
    led_green: THREE.MeshPhysicalMaterial
    led_red: THREE.MeshPhysicalMaterial
    led_yellow: THREE.MeshPhysicalMaterial
    leather10: THREE.MeshStandardMaterial
    SPD_Lacquered_matt_black: THREE.MeshStandardMaterial
    ['HMI-G1 (Graphite1']: THREE.MeshStandardMaterial
    ['HMI- BK (Black)1']: THREE.MeshStandardMaterial
    ['*6']: THREE.MeshStandardMaterial
    ['HMI-G1 (Graph1']: THREE.MeshStandardMaterial
    ['HMI- 3Q01 (Graph1']: THREE.MeshStandardMaterial
    Material: THREE.MeshStandardMaterial
    ['anta_simplicia_cenere-poziom']: THREE.MeshStandardMaterial
    anta_simplicia_cenere: THREE.MeshStandardMaterial
    Color_000: THREE.MeshStandardMaterial
    ['Material.012']: THREE.MeshStandardMaterial
    ['Material.013']: THREE.MeshStandardMaterial
    ['Material.014']: THREE.MeshStandardMaterial
    ['Material.015']: THREE.MeshStandardMaterial
    ['Material.016']: THREE.MeshStandardMaterial
    beton: THREE.MeshPhysicalMaterial
    ['Material.021']: THREE.MeshStandardMaterial
    ['Material.020']: THREE.MeshStandardMaterial
    ['Material.018']: THREE.MeshStandardMaterial
    ['Material.017']: THREE.MeshStandardMaterial
    ['Material.019']: THREE.MeshStandardMaterial
    Big_Buttons: THREE.MeshStandardMaterial
    Small_Buttons: THREE.MeshStandardMaterial
    Chassis: THREE.MeshStandardMaterial
    ['None.003']: THREE.MeshStandardMaterial
    ['Material:007.001']: THREE.MeshStandardMaterial
  }
}

export default function Model({ ...props }: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>(null)
  const { nodes, materials } = useGLTF('/Room.glb') as GLTFResult
  return (
    <group ref={group} {...props} dispose={null}>
      <group
        name='Microphone'
        position={[1.45, 0.74, 0.44]}
        rotation={[-Math.PI, -0.88, -Math.PI]}
        scale={0.11}
      >
        <mesh
          name='body'
          castShadow
          receiveShadow
          geometry={nodes.body.geometry}
          material={materials['Black metal body']}
          position={[-0.37, -5.89, 0.5]}
          rotation={[0, -0.11, 0]}
          scale={[0.41, 0.43, 0.41]}
        />
        <mesh
          name='Object'
          castShadow
          receiveShadow
          geometry={nodes.Object.geometry}
          material={materials['Black metal']}
          position={[-0.37, -5.89, 0.5]}
          scale={[0.42, 0.43, 0.42]}
        />
        <group
          name='record_button'
          position={[-0.37, -6.34, 0.92]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={0.05}
        >
          <mesh
            name='Circle003'
            castShadow
            receiveShadow
            geometry={nodes.Circle003.geometry}
            material={materials['Black metal body']}
          />
          <mesh
            name='Circle003_1'
            castShadow
            receiveShadow
            geometry={nodes.Circle003_1.geometry}
            material={materials.red}
          />
        </group>
        <group
          name='tripod'
          position={[-0.37, -5.89, 0.5]}
          rotation={[0, 0, -Math.PI / 2]}
          scale={0.17}
        >
          <mesh
            name='Circle005'
            castShadow
            receiveShadow
            geometry={nodes.Circle005.geometry}
            material={materials['Black metal body']}
          />
          <mesh
            name='Circle005_1'
            castShadow
            receiveShadow
            geometry={nodes.Circle005_1.geometry}
            material={materials['Black metal']}
          />
        </group>
        <mesh
          name='volume_sensitivity_button'
          castShadow
          receiveShadow
          geometry={nodes.volume_sensitivity_button.geometry}
          material={materials['Black metal body']}
          position={[-0.37, -6.97, 0.91]}
          rotation={[Math.PI / 2, 0, 0]}
          scale={[0.08, 0.07, 0.08]}
        />
        <group name='wire' position={[-0.37, -6.06, 0.5]} scale={0.43}>
          <mesh
            name='Cube042'
            castShadow
            receiveShadow
            geometry={nodes.Cube042.geometry}
            material={materials['Black metal']}
          />
          <mesh
            name='Cube042_1'
            castShadow
            receiveShadow
            geometry={nodes.Cube042_1.geometry}
            material={materials['Black metal inside']}
          />
        </group>
      </group>
      <group
        name='Yamaha_HS5_R'
        position={[1.66, -0.11, 0.13]}
        rotation={[Math.PI, -1.13, Math.PI]}
      >
        <mesh
          name='Cube000'
          castShadow
          receiveShadow
          geometry={nodes.Cube000.geometry}
          material={materials.body}
        />
        <mesh
          name='Cube000_1'
          castShadow
          receiveShadow
          geometry={nodes.Cube000_1.geometry}
          material={materials['Black Metal']}
        />
        <mesh
          name='Cube000_2'
          castShadow
          receiveShadow
          geometry={nodes.Cube000_2.geometry}
          material={materials['White Light']}
        />
        <mesh
          name='Cube000_3'
          castShadow
          receiveShadow
          geometry={nodes.Cube000_3.geometry}
          material={materials['Matte White']}
        />
      </group>
      <group
        name='Yamaha_HS5_L'
        position={[1.64, -0.11, -1.29]}
        rotation={[0, -1.13, 0]}
      >
        <mesh
          name='Cube041'
          castShadow
          receiveShadow
          geometry={nodes.Cube041.geometry}
          material={materials['body.001']}
        />
        <mesh
          name='Cube041_1'
          castShadow
          receiveShadow
          geometry={nodes.Cube041_1.geometry}
          material={materials['Black Metal.001']}
        />
        <mesh
          name='Cube041_2'
          castShadow
          receiveShadow
          geometry={nodes.Cube041_2.geometry}
          material={materials['White Light.001']}
        />
        <mesh
          name='Cube041_3'
          castShadow
          receiveShadow
          geometry={nodes.Cube041_3.geometry}
          material={materials['Matte White.001']}
        />
      </group>
      <group
        name='Midi_Keyboard'
        position={[1.75, 0.78, -0.09]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
      >
        <mesh
          name='Base'
          castShadow
          receiveShadow
          geometry={nodes.Base.geometry}
          material={materials['Material.026']}
        />
        <mesh
          name='Base_1'
          castShadow
          receiveShadow
          geometry={nodes.Base_1.geometry}
          material={materials.None}
        />
        <mesh
          name='Base_2'
          castShadow
          receiveShadow
          geometry={nodes.Base_2.geometry}
          material={materials['Material.027']}
        />
        <mesh
          name='Base_3'
          castShadow
          receiveShadow
          geometry={nodes.Base_3.geometry}
          material={materials['Material.025']}
        />
        <mesh
          name='Base_4'
          castShadow
          receiveShadow
          geometry={nodes.Base_4.geometry}
          material={materials.clear_rubber}
        />
      </group>
      <group
        name='Acoustic_Foam'
        position={[-0.92, 0.48, -1.8]}
        rotation={[Math.PI / 2, 0, 0]}
      >
        <mesh
          name='Cube_Cube001'
          castShadow
          receiveShadow
          geometry={nodes.Cube_Cube001.geometry}
          material={materials['Material.029']}
        />
        <mesh
          name='Cube_Cube001_1'
          castShadow
          receiveShadow
          geometry={nodes.Cube_Cube001_1.geometry}
          material={materials['Material.030']}
        />
        <mesh
          name='Cube_Cube001_2'
          castShadow
          receiveShadow
          geometry={nodes.Cube_Cube001_2.geometry}
          material={materials['Material.033']}
        />
        <mesh
          name='Cube_Cube001_3'
          castShadow
          receiveShadow
          geometry={nodes.Cube_Cube001_3.geometry}
          material={materials['Material.032']}
        />
        <mesh
          name='Cube_Cube001_4'
          castShadow
          receiveShadow
          geometry={nodes.Cube_Cube001_4.geometry}
          material={materials['Material.037']}
        />
        <mesh
          name='Cube_Cube001_5'
          castShadow
          receiveShadow
          geometry={nodes.Cube_Cube001_5.geometry}
          material={materials['Material.036']}
        />
        <mesh
          name='Cube_Cube001_6'
          castShadow
          receiveShadow
          geometry={nodes.Cube_Cube001_6.geometry}
          material={materials['Material.035']}
        />
        <mesh
          name='Cube_Cube001_7'
          castShadow
          receiveShadow
          geometry={nodes.Cube_Cube001_7.geometry}
          material={materials['Material.034']}
        />
        <mesh
          name='Cube_Cube001_8'
          castShadow
          receiveShadow
          geometry={nodes.Cube_Cube001_8.geometry}
          material={materials['Material.041']}
        />
        <mesh
          name='Cube_Cube001_9'
          castShadow
          receiveShadow
          geometry={nodes.Cube_Cube001_9.geometry}
          material={materials['Material.038']}
        />
        <mesh
          name='Cube_Cube001_10'
          castShadow
          receiveShadow
          geometry={nodes.Cube_Cube001_10.geometry}
          material={materials['Material.045']}
        />
        <mesh
          name='Cube_Cube001_11'
          castShadow
          receiveShadow
          geometry={nodes.Cube_Cube001_11.geometry}
          material={materials['Material.042']}
        />
      </group>
      <mesh
        name='Audio_Interface'
        castShadow
        receiveShadow
        geometry={nodes.Audio_Interface.geometry}
        material={materials['Material.050']}
        position={[1.74, 0.8, -1.01]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={0.01}
      >
        <mesh
          name='inside_darkening_cube'
          castShadow
          receiveShadow
          geometry={nodes.inside_darkening_cube.geometry}
          material={materials.jacks_noir}
          position={[0.01, -0.39, -0.28]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={[17.77, 3.38, 3.7]}
        />
        <mesh
          name='faceplate_back'
          castShadow
          receiveShadow
          geometry={nodes.faceplate_back.geometry}
          material={materials['Material.053']}
          position={[0.01, -10.3, -0.33]}
          rotation={[0, 0, -Math.PI]}
        >
          <mesh
            name='back_fixing_screws'
            castShadow
            receiveShadow
            geometry={nodes.back_fixing_screws.geometry}
            material={materials['Material.050']}
            position={[0, -0.02, 0]}
            scale={0.17}
          />
          <mesh
            name='dock_connector'
            castShadow
            receiveShadow
            geometry={nodes.dock_connector.geometry}
            material={materials['Material.049']}
            position={[-6.02, 0.1, 1.86]}
            rotation={[Math.PI / 2, 0, Math.PI]}
          />
          <group
            name='firewire_connector'
            position={[-12.72, -0.42, 1.19]}
            rotation={[Math.PI / 2, 0, Math.PI]}
          >
            <mesh
              name='Cube005'
              castShadow
              receiveShadow
              geometry={nodes.Cube005.geometry}
              material={materials.chrome}
            />
            <mesh
              name='Cube005_1'
              castShadow
              receiveShadow
              geometry={nodes.Cube005_1.geometry}
              material={materials.jacks_noir}
            />
          </group>
          <mesh
            name='hybrid_jack_1'
            castShadow
            receiveShadow
            geometry={nodes.hybrid_jack_1.geometry}
            material={materials.jacks_noir}
            position={[13.93, 0.94, -0.48]}
            scale={0.85}
          />
          <mesh
            name='hybrid_jack_2'
            castShadow
            receiveShadow
            geometry={nodes.hybrid_jack_2.geometry}
            material={materials.jacks_noir}
            position={[7.9, 0.94, -0.48]}
            scale={0.85}
          />
          <mesh
            name='hybrid_jacks_fixing_srews'
            castShadow
            receiveShadow
            geometry={nodes.hybrid_jacks_fixing_srews.geometry}
            material={materials['Material.050']}
            position={[6.15, 0.09, -2.32]}
            rotation={[Math.PI, 0, Math.PI]}
            scale={0.19}
          />
          <group
            name='jack_ctrlrm_1'
            position={[2.95, 0.17, -1.83]}
            rotation={[0, 0.3, 0]}
            scale={0.88}
          >
            <mesh
              name='Circle009'
              castShadow
              receiveShadow
              geometry={nodes.Circle009.geometry}
              material={materials.chrome}
            />
            <mesh
              name='Circle009_1'
              castShadow
              receiveShadow
              geometry={nodes.Circle009_1.geometry}
              material={materials.jacks_noir}
            />
          </group>
          <group
            name='jack_ctrlrm_2'
            position={[2.95, 0.17, 1.47]}
            rotation={[0, 0.3, 0]}
            scale={0.88}
          >
            <mesh
              name='Circle008'
              castShadow
              receiveShadow
              geometry={nodes.Circle008.geometry}
              material={materials.chrome}
            />
            <mesh
              name='Circle008_1'
              castShadow
              receiveShadow
              geometry={nodes.Circle008_1.geometry}
              material={materials.jacks_noir}
            />
          </group>
          <group
            name='power_connector'
            position={[-15.68, -0.83, 0.83]}
            rotation={[Math.PI / 2, 0, Math.PI]}
          >
            <mesh
              name='Cube006'
              castShadow
              receiveShadow
              geometry={nodes.Cube006.geometry}
              material={materials.jacks_noir}
            />
            <mesh
              name='Cube006_1'
              castShadow
              receiveShadow
              geometry={nodes.Cube006_1.geometry}
              material={materials.chrome}
            />
          </group>
        </mesh>
        <mesh
          name='faceplate_front'
          castShadow
          receiveShadow
          geometry={nodes.faceplate_front.geometry}
          material={materials['Material.053']}
          position={[0.01, 9.61, -0.33]}
        >
          <group
            name='button_phantom_power'
            position={[1.34, 0.32, 1.53]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.03}
          >
            <mesh
              name='Sphere015'
              castShadow
              receiveShadow
              geometry={nodes.Sphere015.geometry}
              material={materials['48V']}
            />
            <mesh
              name='Sphere015_1'
              castShadow
              receiveShadow
              geometry={nodes.Sphere015_1.geometry}
              material={materials['Material.051']}
            />
          </group>
          <group
            name='button_source_1'
            position={[-16, 0.32, 1.53]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.03}
          >
            <mesh
              name='Sphere017'
              castShadow
              receiveShadow
              geometry={nodes.Sphere017.geometry}
              material={materials['Material.052']}
            />
            <mesh
              name='Sphere017_1'
              castShadow
              receiveShadow
              geometry={nodes.Sphere017_1.geometry}
              material={materials['Material.051']}
            />
          </group>
          <group
            name='button_source_2'
            position={[-1.24, 0.32, 1.53]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.03}
          >
            <mesh
              name='Sphere016'
              castShadow
              receiveShadow
              geometry={nodes.Sphere016.geometry}
              material={materials['Material.052']}
            />
            <mesh
              name='Sphere016_1'
              castShadow
              receiveShadow
              geometry={nodes.Sphere016_1.geometry}
              material={materials['Material.051']}
            />
          </group>
          <mesh
            name='front_fixing_screws'
            castShadow
            receiveShadow
            geometry={nodes.front_fixing_screws.geometry}
            material={materials['Material.050']}
            position={[-18.71, -0.88, 0.03]}
            scale={0.17}
          />
          <group
            name='jack_headphones_1'
            position={[14.78, 0, -1.96]}
            rotation={[0, -0.79, 0]}
            scale={0.88}
          >
            <mesh
              name='Circle010'
              castShadow
              receiveShadow
              geometry={nodes.Circle010.geometry}
              material={materials.chrome}
            />
            <mesh
              name='Circle010_1'
              castShadow
              receiveShadow
              geometry={nodes.Circle010_1.geometry}
              material={materials.jacks_noir}
            />
          </group>
          <group
            name='Jack_onyx'
            position={[14.78, 0, 1.33]}
            rotation={[0, 0.3, 0]}
            scale={0.88}
          >
            <mesh
              name='Circle011'
              castShadow
              receiveShadow
              geometry={nodes.Circle011.geometry}
              material={materials.chrome}
            />
            <mesh
              name='Circle011_1'
              castShadow
              receiveShadow
              geometry={nodes.Circle011_1.geometry}
              material={materials.jacks_noir}
            />
          </group>
          <mesh
            name='knob_gain_1'
            castShadow
            receiveShadow
            geometry={nodes.knob_gain_1.geometry}
            material={materials['Material.052']}
            position={[-12.66, 3.22, 0.65]}
            rotation={[0, 0.97, 0]}
          >
            <mesh
              name='Sphere003'
              castShadow
              receiveShadow
              geometry={nodes.Sphere003.geometry}
              material={materials['Material.051']}
              position={[0, -3.15, 0]}
            />
          </mesh>
          <mesh
            name='knob_gain_2'
            castShadow
            receiveShadow
            geometry={nodes.knob_gain_2.geometry}
            material={materials['Material.052']}
            position={[-4.72, 3.22, 0.65]}
            rotation={[0, 0.97, 0]}
          >
            <mesh
              name='Sphere002'
              castShadow
              receiveShadow
              geometry={nodes.Sphere002.geometry}
              material={materials['Material.051']}
              position={[0, -3.15, 0]}
            />
          </mesh>
          <mesh
            name='knob_phones_2'
            castShadow
            receiveShadow
            geometry={nodes.knob_phones_2.geometry}
            material={materials['Material.052']}
            position={[10.71, 3.22, 0.65]}
            rotation={[0, 0.97, 0]}
          >
            <mesh
              name='Sphere001'
              castShadow
              receiveShadow
              geometry={nodes.Sphere001.geometry}
              material={materials['Material.051']}
              position={[0, -3.15, 0]}
            />
          </mesh>
          <mesh
            name='leds_green'
            castShadow
            receiveShadow
            geometry={nodes.leds_green.geometry}
            material={materials.led_green}
            position={[2.82, -0.04, -0.89]}
            scale={0.24}
          />
          <mesh
            name='leds_red'
            castShadow
            receiveShadow
            geometry={nodes.leds_red.geometry}
            material={materials.led_red}
            position={[-7.73, -0.04, -0.94]}
            scale={0.24}
          />
          <mesh
            name='leds_yellow'
            castShadow
            receiveShadow
            geometry={nodes.leds_yellow.geometry}
            material={materials.led_yellow}
            position={[-7.73, -0.04, 0.03]}
            scale={0.24}
          />
          <mesh
            name='onyx_knob_body'
            castShadow
            receiveShadow
            geometry={nodes.onyx_knob_body.geometry}
            material={materials['Material.052']}
            position={[5.9, 3.22, 0.65]}
            rotation={[0, 0.97, 0]}
          >
            <mesh
              name='onyx_knob_cap'
              castShadow
              receiveShadow
              geometry={nodes.onyx_knob_cap.geometry}
              material={materials['Material.051']}
              position={[0, -3.15, 0]}
            />
          </mesh>
        </mesh>
      </mesh>
      <group
        name='Sofa'
        position={[-0.82, -1, 1.31]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          name='Calligaris_Relax_Sofas_Maurice_CS33462525_Component_01'
          castShadow
          receiveShadow
          geometry={
            nodes.Calligaris_Relax_Sofas_Maurice_CS33462525_Component_01
              .geometry
          }
          material={materials.leather10}
        />
        <mesh
          name='Calligaris_Relax_Sofas_Maurice_CS33462525_Component_01_1'
          castShadow
          receiveShadow
          geometry={
            nodes.Calligaris_Relax_Sofas_Maurice_CS33462525_Component_01_1
              .geometry
          }
          material={materials.SPD_Lacquered_matt_black}
        />
      </group>
      <group
        name='Chair'
        position={[0.92, -0.5, -0.62]}
        rotation={[0, 1.09, 0]}
      >
        <mesh
          name='HSeatPan'
          castShadow
          receiveShadow
          geometry={nodes.HSeatPan.geometry}
          material={materials['HMI-G1 (Graphite1']}
        />
        <mesh
          name='HSeatPan_1'
          castShadow
          receiveShadow
          geometry={nodes.HSeatPan_1.geometry}
          material={materials['HMI- BK (Black)1']}
        />
        <mesh
          name='HSeatPan_2'
          castShadow
          receiveShadow
          geometry={nodes.HSeatPan_2.geometry}
          material={materials['*6']}
        />
        <mesh
          name='HSeatPan_3'
          castShadow
          receiveShadow
          geometry={nodes.HSeatPan_3.geometry}
          material={materials['HMI-G1 (Graph1']}
        />
        <mesh
          name='HSeatPan_4'
          castShadow
          receiveShadow
          geometry={nodes.HSeatPan_4.geometry}
          material={materials['HMI- 3Q01 (Graph1']}
        />
      </group>
      <group name='Storage' position={[-1.73, -1, -1.32]}>
        <mesh
          name='G-__555699'
          castShadow
          receiveShadow
          geometry={nodes['G-__555699'].geometry}
          material={materials.Material}
        />
        <mesh
          name='G-__555699_1'
          castShadow
          receiveShadow
          geometry={nodes['G-__555699_1'].geometry}
          material={materials['anta_simplicia_cenere-poziom']}
        />
      </group>
      <group
        name='Table'
        position={[1.92, -1, -1.84]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          name='G-__555564'
          castShadow
          receiveShadow
          geometry={nodes['G-__555564'].geometry}
          material={materials.Material}
        />
        <mesh
          name='G-__555564_1'
          castShadow
          receiveShadow
          geometry={nodes['G-__555564_1'].geometry}
          material={materials.anta_simplicia_cenere}
        />
      </group>
      <group
        name='Shelf'
        position={[1.92, 0.77, 0.21]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          name='G-__555609'
          castShadow
          receiveShadow
          geometry={nodes['G-__555609'].geometry}
          material={materials.anta_simplicia_cenere}
        />
        <mesh
          name='G-__555609_1'
          castShadow
          receiveShadow
          geometry={nodes['G-__555609_1'].geometry}
          material={materials.Material}
        />
      </group>
      <group name='Cabinet' position={[1.27, -1, 1.78]}>
        <mesh
          name='G-__555690'
          castShadow
          receiveShadow
          geometry={nodes['G-__555690'].geometry}
          material={materials.Material}
        />
        <mesh
          name='G-__555690_1'
          castShadow
          receiveShadow
          geometry={nodes['G-__555690_1'].geometry}
          material={materials.anta_simplicia_cenere}
        />
        <mesh
          name='G-__555690_2'
          castShadow
          receiveShadow
          geometry={nodes['G-__555690_2'].geometry}
          material={materials.Color_000}
        />
      </group>
      <group
        name='Stand'
        position={[1.7, -0.07, -0.6]}
        rotation={[0, -Math.PI / 2, 0]}
        scale={0.21}
      >
        <mesh
          name='Cylinder'
          castShadow
          receiveShadow
          geometry={nodes.Cylinder.geometry}
          material={materials['Material.012']}
        />
        <mesh
          name='Cylinder_1'
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_1.geometry}
          material={materials['Material.013']}
        />
        <mesh
          name='Cylinder_2'
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_2.geometry}
          material={materials['Material.014']}
        />
        <mesh
          name='Cylinder_3'
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_3.geometry}
          material={materials['Material.015']}
        />
        <mesh
          name='Cylinder_4'
          castShadow
          receiveShadow
          geometry={nodes.Cylinder_4.geometry}
          material={materials['Material.016']}
        />
      </group>
      <group
        name='Room_Frame'
        position={[2.07, -1, -1.99]}
        rotation={[-Math.PI, 0, -Math.PI]}
      >
        <mesh
          name='G-__555762'
          castShadow
          receiveShadow
          geometry={nodes['G-__555762'].geometry}
          material={materials['HMI- 3Q01 (Graph1']}
        />
        <mesh
          name='G-__555762_1'
          castShadow
          receiveShadow
          geometry={nodes['G-__555762_1'].geometry}
          material={materials.beton}
        />
        <mesh
          name='Name'
          castShadow
          receiveShadow
          geometry={nodes.Name.geometry}
          material={nodes.Name.material}
          position={[0.15, 1.4, -3.7]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
        />
      </group>
      <group
        name='Monitor'
        position={[1.64, 0.05, -0.6]}
        rotation={[Math.PI / 2, 0, Math.PI / 2]}
        scale={[0.52, 0.21, 0.2]}
      >
        <mesh
          name='Plane'
          castShadow
          receiveShadow
          geometry={nodes.Plane.geometry}
          material={materials['Material.021']}
        />
        <mesh
          name='Plane_1'
          castShadow
          receiveShadow
          geometry={nodes.Plane_1.geometry}
          material={materials['Material.020']}
        />
        <mesh
          name='Plane_2'
          castShadow
          receiveShadow
          geometry={nodes.Plane_2.geometry}
          material={materials['Material.014']}
        />
        <mesh
          name='Plane_3'
          castShadow
          receiveShadow
          geometry={nodes.Plane_3.geometry}
          material={materials['Material.018']}
        />
        <mesh
          name='Plane_4'
          castShadow
          receiveShadow
          geometry={nodes.Plane_4.geometry}
          material={materials['Material.017']}
        />
        <mesh
          name='Plane_5'
          castShadow
          receiveShadow
          geometry={nodes.Plane_5.geometry}
          material={materials['Material.019']}
        />
      </group>
      <group
        name='Keyboard'
        position={[1.34, -0.25, -0.44]}
        rotation={[1.58, 0.13, 1.57]}
        scale={0.1}
      >
        <mesh
          name='Big_Buttons001'
          castShadow
          receiveShadow
          geometry={nodes.Big_Buttons001.geometry}
          material={materials.Big_Buttons}
        />
        <mesh
          name='Big_Buttons001_1'
          castShadow
          receiveShadow
          geometry={nodes.Big_Buttons001_1.geometry}
          material={materials.Small_Buttons}
        />
        <mesh
          name='Big_Buttons001_2'
          castShadow
          receiveShadow
          geometry={nodes.Big_Buttons001_2.geometry}
          material={materials.Chassis}
        />
      </group>
      <group
        name='Camera'
        position={[1.82, 0.47, -0.56]}
        rotation={[Math.PI / 2, 0, 0]}
        scale={0.07}
      >
        <mesh
          name='camera001'
          castShadow
          receiveShadow
          geometry={nodes.camera001.geometry}
          material={materials['None.003']}
        />
        <mesh
          name='camera001_1'
          castShadow
          receiveShadow
          geometry={nodes.camera001_1.geometry}
          material={materials['Material:007.001']}
        />
      </group>
    </group>
  )
}

useGLTF.preload('/Room.glb')
