import type { NextPage } from 'next'
import Head from 'next/head'
import HomeCanvas from '../components/Home/HomeCanvas'
import NameRole from '../components/Home/NameRole'
import HomeOverlay from '../components/Home/ViewerControl'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Yiyun Jia</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <HomeCanvas />
        <HomeOverlay />
        <NameRole />
      </main>
    </div>
  )
}

export default Home
